Renew CI Workflow
Goboolean/core-system.worker pull request #148
Opened 2024-06-26 11:13 UTC by ffvv0123

2024-06-26 11:15 UTC, mulmuri commented on .github/workflows/ci.yml
> +              golint -set_exit_status ./...
EOL 추가해주세요

2024-06-26 11:16 UTC, mulmuri commented on .github/workflows/ci.yml
> +          run: go test ./...
Makefile에서 테스트 명령어를 정의해서 make test 로 실행할 수 있도록 해주세요! 다른 부분도 마찬가지

2024-06-26 11:18 UTC, mulmuri commented on .github/workflows/ci.yml
> +  push:
main에 대해 push / pr 트리거 넣어주세요. feat는 필요없습니당 (hts-connector 참고)

2024-06-26 11:49 UTC, ffvv0123 commented on .github/workflows/ci.yml
> +  push:
수정했습니다!

2024-06-26 11:55 UTC, mulmuri commented on .github/workflows/ci.yml
> +      - name: Setup Go
가독성을 위해 step 마다 줄 하나씩 추가해주세요

2024-06-26 11:57 UTC, mulmuri commented on .github/workflows/ci.yml
> +          go get golang.org/x/lint/golint
설치하는 단계랑 실행하는 단계를 분리해주세요

2024-06-26 12:00 UTC, mulmuri requested changes
수정사항 반영하고나서 @lsjtop10 님이 lint 이슈 해결해주세요!

2024-06-26 13:32 UTC, mulmuri commented on .github/workflows/ci.yml
> +        run: test -z $(gofmt -l .)
이거 어떻게 동작하는지 간단하게 설명해주세요

2024-06-26 13:35 UTC, mulmuri commented on .github/workflows/ci.yml
> +          go get golang.org/x/lint/golint
go get 말고 go install 사용해주세요. 차이는 검색 ㄱㄱ

2024-06-26 13:40 UTC, mulmuri commented on .github/workflows/ci.yml
> +          golint -set_exit_status ./...
flag 의미 설명해주세요

2024-06-26 14:32 UTC, mulmuri requested changes

2024-06-26 14:32 UTC, mulmuri commented on Makefile
> +	go test ./...
EOF

2024-06-26 15:03 UTC, merged

2024-06-27 00:15 UTC, lsjtop10 commented
@mulmuri 지금 PR 깨지는 건 파이프라인 쪽 작업이 덜 돼서 발생하는 것 같습니다. 파이프라인 쪽 작업이 완료되면 lint 성공할 것 같습니다.