Implement mock model exec job
Goboolean/core-system.worker pull request #40
Opened 2024-04-11 04:30 UTC by lsjtop10

# 변경 내용 요약

KServe Client 인터페이스를 이용해 KServe모델에 요청을 보내고 받는 부분을 구현했습니다.

2024-04-15 12:43 UTC, mulmuri commented on internal/infrastructure/kserve.go
> +type KServeClientImpl struct {
앞으로 계속 Impl 접미사 사용하실 예정이신가요??

2024-04-15 12:52 UTC, lsjtop10 commented on internal/infrastructure/kserve.go
> +type KServeClientImpl struct {
고민되는 부분인데 -er로 인터페이스 이름을 나타내기 힘들다면 써야 하지 않을까 생각하고 있습니다.

2024-04-15 12:52 UTC, lsjtop10 commented on internal/infrastructure/kserve.go
> +type KServeClientImpl struct {
아니면 인터페이스 이름을 -port로 짓는 것은 어떨까요?

2024-04-15 12:53 UTC, lsjtop10 commented on internal/infrastructure/kserve.go
> +package infrastructure
네, 좋습니다. mongodb도 패키지를 나누지 않으니 하나의 파일에 너무 많은 코드가 들어가더라고요. 이번 리펙토링 하는 김에 이 작업도 같이 하겠습니다.

2024-04-15 13:01 UTC, mulmuri commented on internal/infrastructure/kserve.go
> +type KServeClientImpl struct {
실제 헥사고날 아키텍처의 개념을 사용하고 있는게 아니라 혼동이 올 수 있을 것 같습니다..! 뭔가 Impl 은 많이 낮서네요.. ㅎㅎ

2024-04-15 13:04 UTC, mulmuri commented on internal/job/mock-model-exec.go
> +	go func() {
graceful shutdown 개념과 관련하여, 이 class 의 Close 메서드를 호출하였을 때 메서드의 종료가 고루틴의 안전한 종료를 보장하도록 작성하는 것이 필요해보입니다. sync.wg 를 통해 해결할 수 있습니다.

2024-04-15 13:08 UTC, mulmuri requested changes

2024-04-15 13:08 UTC, mulmuri commented on internal/job/mock-model-exec.go
> +	go func() {
graceful shutdown 개념과 관련하여, 이 class 의 Close 메서드를 호출하였을 때 메서드의 종료가 고루틴의 안전한 종료를 보장하도록 작성하는 것이 필요해보입니다. sync.wg 를 통해 해결할 수 있습니다.

2024-04-15 13:16 UTC, lsjtop10 commented on internal/job/mock-model-exec.go
> +	go func() {
네, 수정하겠습니다.

2024-04-15 13:33 UTC, lsjtop10 commented on internal/job/mock-model-exec.go
> +	go func() {
요청하신 사항은 수정하겠습니다.

2024-04-16 11:43 UTC, mulmuri approved these changes

2024-04-16 11:50 UTC, merged

2024-04-16 11:50 UTC, lsjtop10 commented
resolve #40