Fix example job
Goboolean/core-system.worker pull request #43
Opened 2024-04-11 05:02 UTC by lsjtop10

- 사용자 파라미터 초기화 하는 예제 수정
- Execute에서 고루틴이 끝나기 전에 out 채널 닫히는 문제 수정
- 고루틴에 반복문 없는 문제 수정

2024-04-11 05:03 UTC, lsjtop10 commented
resolve #42

2024-04-15 13:06 UTC, mulmuri commented on internal/job/example.go
>  	go func() {
다른 PR 에서 지적했던 부분인데, graceful shutdown 이 적용되면 좋을 것 같습니다!

2024-04-15 13:09 UTC, mulmuri requested changes

2024-04-15 13:09 UTC, mulmuri commented on internal/job/example.go
>  	go func() {
다른 PR 에서 지적했던 부분인데, graceful shutdown 이 적용되면 좋을 것 같습니다!

2024-04-16 11:44 UTC, mulmuri approved these changes

2024-04-16 11:51 UTC, lsjtop10 commented
resolve #43

2024-04-16 11:51 UTC, merged