Feat: pipeline builder
Goboolean/core-system.worker pull request #64
Opened 2024-05-09 08:55 UTC by lsjtop10

application configuration을 바탕으로 실제 pipeline 객체를 생성하는 부분을 구현했습니다. 

- pipline이 job을 아는 기존의 의존성을 최대한 이용하기 위해 mapper또한 job에 배치
- 의존성이 한 방향으로 흐를 수 있도록 구현

2024-05-09 10:48 UTC, mulmuri commented on internal/pipeline/builder.go
> +	configString, _ := yaml.Marshal(config)
예외처리 필요하지 않을까요?

2024-05-09 12:17 UTC, lsjtop10 commented on internal/pipeline/builder.go
> +	if AdapterIsRequred{
네 그렇네요. 수정하겠습니다.

2024-05-09 12:55 UTC, lsjtop10 commented on internal/pipeline/builder.go
> +	configString, _ := yaml.Marshal(config)
에러 메시지 생성하는 부분이라 필요 없을 것이라고 생각했는데 생각해보니 아닌 것 같군요. ymal 라이브러리를 이용하면 에러를 반환할 수 있으니 다른 방법을 찾아봐야 할 것 같네요.

2024-05-09 13:02 UTC, mulmuri commented on internal/pipeline/builder.go
> +	} else if config.Model.Id != "" {
else if 는 condition chain 을 복잡하게 만든다고 생각해요. 제가 생각하는 클린 코드는 핸들링 컨디션이 아닌 상황이 끝까지 가는 것입니다. 이 경우에 condition chain 이 가장 단순하며, 불가피한 경우에만 else if 등을 사용하거나 if 내부에서 if 를 사용해야 된다고 생각해요.

if A -> return error
if B -> return error
...
return nil

2024-05-09 14:01 UTC, lsjtop10 commented on internal/pipeline/builder.go
> +	} else if config.Model.Id != "" {
이 부분은 내일 생각을 정리해서 다시 말씀드리겠습니다.

2024-05-10 02:28 UTC, lsjtop10 commented on internal/pipeline/builder.go
> +	} else if config.Model.Id != "" {
else if 문을 사용하면 앞의 조건이 뒤의 조건에 영향을 주기 때문에 높은 인지 부하를 유발하는 코드를 작성할 위험이 있다고 생각합니다. else if문에서 체크하는 condition을 다른 condition과 상관 없이 독립적으로 작성하려고 노력하면 해결할 수 있는 문제이지만 구조적으로 앞의 조건에 연관된 조건을 체크하도록 유도하는 것 같습니다. 따라서 되도록 if 문으로 eraly return하는 방향이 바람직한 것 같긴 합니다. 하지만 중첩된 if문을 사용해야 한다는 부분에는 동의하기 어렵습니다. if 문이 중첩되면 내부에서 조건 분기가 이루어질 때마다 외부 조건을 기억해야 해서 높은 인지 부하를 유발합니다. 이는 else if문보다 더 좋지 않다고 생각해요

2024-05-10 02:53 UTC, mulmuri commented on internal/pipeline/builder.go
> +	} else if config.Model.Id != "" {
불가피한 경우에만 중첩 if문을 사용해야 하고, 가능하면 if문으로 return 시키는게 좋다는 의미였어요 ㅎㅎ

2024-05-10 05:28 UTC, mulmuri commented on internal/pipeline/builder.go
> +	} else if config.Model.Id != "" {
이거 수정 된건가요?

2024-05-11 05:56 UTC, mulmuri requested changes
수정하고 리퀘 다시 주세요 ㅎㅎ

2024-05-13 01:44 UTC, mulmuri approved these changes

2024-05-13 02:17 UTC, merged