Fix: fix NotifiStop because a block occures in the if statement
Goboolean/core-system.worker pull request #80
Opened 2024-05-17 08:43 UTC by lsjtop10

```go
	if _, ok := <-sn.ch; ok {
		close(sn.ch)
	}
```
if문에서 `_, ok := <-sn.ch;`이 전체 프로그램의 Block를 발생시키는 문제가 있었습니다. 원래 의도는 ok필드를 검사해 닫힌 채널인지 알아보고자 했던 것이었습니다. 그런데 해당 채널에 데이터가 들어오지 않으니 데이터가 들어올 때까지 대기하는 문제가 있었습니다. 이를 해결하기 위해 다른 방법을 사용했습니다.

2024-05-17 10:35 UTC, mulmuri requested changes

2024-05-17 10:35 UTC, mulmuri commented on internal/util/stop_notifier.go
> +	sn.ch = closedchan
잘 동작하는지 테스트코드로 검증해주세요 이미 기존 채널을 구독하고 있을 때 이 행위를 한다고 closedchan으로 바뀌지 않을 것 같은 느낌이 드네요

2024-05-17 10:42 UTC, lsjtop10 commented on internal/util/stop_notifier.go
> +	sn.ch = closedchan
네, 검증하는 코드 추가해서 올리겠습니다.

2024-05-20 00:22 UTC, lsjtop10 commented
테스트 추가했습니다.

2024-05-20 06:13 UTC, mulmuri approved these changes

2024-05-20 06:13 UTC, merged