Feat: implement same sequnce number joinner
Goboolean/core-system.worker pull request #81
Opened 2024-05-17 08:44 UTC by lsjtop10

2024-05-17 08:45 UTC, lsjtop10 commented
[772bbc5](https://github.com/Goboolean/core-system.worker/pull/81/commits/772bbc54f13065b7bc204cb0c25fd4eeb8be9d94)위 커밋이 중요한 커밋이니 리뷰할 때 중점적으로 보시면 됩니다.

2024-05-17 09:53 UTC, mulmuri commented on internal/job/joinner/by_sequnce_num.go
> +type BySequnceNum struct {
구조체의 이름이 명사꼴이면 더 좋을 것 같아요 작명이 쉽지는 않지만 ㅠ

2024-05-17 10:32 UTC, mulmuri requested changes

2024-05-17 10:40 UTC, lsjtop10 commented on internal/job/joinner/by_sequnce_num.go
> +		b.wg.Add(1)
어 실수했네요. 수정하겠습니다.

2024-05-17 11:52 UTC, lsjtop10 commented on internal/job/joinner/by_sequnce_num.go
> +	var i int = 0
네, 수정했습니다.

2024-05-17 11:55 UTC, lsjtop10 commented on internal/job/joinner/by_sequnce_num_test.go
> +		if err != nil {
arrange 단계에서 오류가 발생했기 때문에 더 이상 진행이 불가능하다는 의미에서 panic을 사용했습니다. arrange 단계에서 발생하는 오류는 assert단계에서 검증하고자 하는 에러와는 구분돼야 한다고 생각해요. 그런 이유 때문에라도 assert.NoError를 사용하지 않았습니다.

2024-05-17 11:55 UTC, lsjtop10 commented on internal/job/joinner/by_sequnce_num.go
> +	len := len(data)
네, 수정하겠습니다.

2024-05-17 12:04 UTC, lsjtop10 commented on internal/job/joinner/by_sequnce_num.go
> +type BySequnceNum struct {
동어반복을 피하려면 형용사구로 짓는 방법을 쓸 수밖에 없더라고요. 그런데 명사꼴로 짓는다면 SequnceNum라는 방법도 있겠네요. 어떤가요?

2024-05-17 12:05 UTC, lsjtop10 commented on internal/job/joinner/by_sequnce_num.go
> +func findLargestPacketIndexBySequence(data []model.Packet, target int64) int {
구조체의 필드가 필요하지 않고 외부에서 호출되는 함수도 아니며 구조체의 중심 주제와 조금 동떨어져있다고 생각하기 때문입니다. 더군다나 고언어의 패러다임상 모든 함수를 구조체 안에 넣을 필요가 없다는 생각이 듭니다. 모든 것을 객체 안에 넣는 강력한 객체지향을 추구하지 않기 때문입니다.

2024-05-17 12:28 UTC, mulmuri commented on internal/job/joinner/by_sequnce_num_test.go
> +		if err != nil {
차라리 이렇게 if문으로 처리하는게 낫지 panic을 테스트코드에서 사용하는건 바람직하지 않은 것 같아요. 실제로도 패닉은 코드의 중단을 위해서 사용하는게 아니라 핸들링할 수 없는 매우 중요한 오류가 있을때 사용하니까요..!
```go
if !assert.NoError(err) {
  return
}
```

2024-05-18 06:59 UTC, lsjtop10 commented on internal/job/joinner/by_sequnce_num.go
> +	var i int = 0
예약어 사용 자제

2024-05-20 06:12 UTC, mulmuri approved these changes

2024-05-20 08:05 UTC, merged

2024-05-27 04:19 UTC, lsjtop10 commented
#73